sudo: false
language: java
os:
  - osx

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in src/travis/certs/dev_id.cer.enc -d -a -out src/travis/certs/dev_id.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in src/travis/certs/dev_id.p12.enc -d -a -out src/travis/certs/dev_id.p12
  - ./src/travis/add-key.sh

script:
  - codesign -fs "Developer ID Application" -v Gephi.app

after_script:
  - ./src/travis/remove-key.sh
